# What is numpy ?

Numpy is the fundamental package foe scientific computing in Python. It is a Python Library that provides a multidimensional array objects , various derived objects(such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulations,sorting and much more

In [2]:
# creating Numpy arrays

import numpy as np

a=np.array([1,2,3])  # this is 1D array
a

array([1, 2, 3])

In [3]:
type(a)

numpy.ndarray

In [4]:
b=np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
b.ndim   # to check the dimensions 

2

In [11]:
c= np.array([[[1,2,3,4],
            [4,5,6,7]],
            [[6,7,8,9],[1,6,7,8]]])
c.ndim

3

In [12]:
c

array([[[1, 2, 3, 4],
        [4, 5, 6, 7]],

       [[6, 7, 8, 9],
        [1, 6, 7, 8]]])

In [13]:
f=np.array([[1,2,3],[4,5,6]],dtype=float)

In [14]:
f

array([[1., 2., 3.],
       [4., 5., 6.]])

In [15]:
r=np.array([[1,0,3],[0,5,6]],dtype=bool)

In [16]:
r

array([[ True, False,  True],
       [False,  True,  True]])

In [17]:
np_range=np.arange(0,10)
np_range

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
np_range=np.arange(0,10,2)
np_range

array([0, 2, 4, 6, 8])

In [24]:
print(b)
np_reshape=b.reshape(3,2)
print("_____________________")
print(np_reshape)

[[1 2 3]
 [4 5 6]]
_____________________|
[[1 2]
 [3 4]
 [5 6]]


In [26]:
np_range_with_reshape=np.arange(0,10).reshape(5,2)
np_range_with_reshape

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [29]:
# np.ones and np.zeros

np.ones((3,4),dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [31]:
np.zeros((3,4),dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [36]:
# np.random
np.random.random((3,4))

array([[0.44222921, 0.83169312, 0.36866795, 0.59902587],
       [0.43307171, 0.9495575 , 0.01419401, 0.59728057],
       [0.45855526, 0.37575884, 0.33005845, 0.0793633 ]])

In [37]:
# np.linspace

np.linspace(-10,10,20)

array([-10.        ,  -8.94736842,  -7.89473684,  -6.84210526,
        -5.78947368,  -4.73684211,  -3.68421053,  -2.63157895,
        -1.57894737,  -0.52631579,   0.52631579,   1.57894737,
         2.63157895,   3.68421053,   4.73684211,   5.78947368,
         6.84210526,   7.89473684,   8.94736842,  10.        ])

In [39]:
# np.identity 
np.identity(4,dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [49]:
a1=np.arange(10)  # vetor
a2=np.arange(12,dtype=float).reshape(4,3) # matrix 
a3=np.arange(12,dtype=int).reshape(2,2,3)

In [50]:
print(a1)
print("_______")
print(a2)
print("_______")
print(a3)
print("_______")

[0 1 2 3 4 5 6 7 8 9]
_______
[[ 0.  1.  2.]
 [ 3.  4.  5.]
 [ 6.  7.  8.]
 [ 9. 10. 11.]]
_______
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
_______


In [51]:
# shape
a1.shape

(10,)

In [52]:
a2.shape

(4, 3)

In [53]:
a3.shape

(2, 2, 3)

In [54]:
# itemsixze
a3.itemsize

4

In [55]:
a2.itemsize

8

In [56]:
# dtype
a1.dtype


dtype('int32')

In [57]:
a2.dtype

dtype('float64')

# Array Operations

In [61]:
a1= np.arange(12).reshape(3,4)
a2= np.arange(12,24).reshape(3,4)
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [63]:
np.add(a1,a2)

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [64]:
a1 + a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [66]:
a1 * a2 

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

In [69]:
# relatinal

a2>15

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

# aRRAY fUNCRION


In [70]:
a1= np.random.random((3,3))
a2= np.round(a1 * 100)

In [72]:
# mx/min/sum/prod
print(np.max(a1))
print(np.min(a1))
print(np.sum(a1))
print(np.prod(a1))

0.8519873595972891
0.016623796863547535
4.018609508893359
1.732112766055324e-05


In [73]:
# mean / median / mode /std /var
# 0 -> column and 1 -> row

np.mean(a1,axis=1)

array([0.25292918, 0.40927933, 0.67732799])

In [74]:
np.std(a1,axis=1)

array([0.25476521, 0.17500627, 0.23866104])

In [75]:
# dot prodect
a2=np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

In [76]:
np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [77]:
# log and exponents 
np.log(a1)

array([[-0.49985419, -1.99845433, -4.09692006],
       [-1.03564404, -0.4376688 , -1.48148115],
       [-0.16018359, -0.17421445, -1.07916294]])

In [78]:
np.exp(a1)

array([[1.8342196 , 1.1451603 , 1.01676274],
       [1.42617734, 1.90701568, 1.25520734],
       [2.34430119, 2.31663735, 1.40477888]])

In [79]:
# ravel # which change ant dim to 1 d array
a3

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [80]:
a3.ravel()

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

# stacking 

stacking is nothing when we need to add for different area of data we will use 

In [81]:
a4= np.arange(12).reshape(3,4)
a5= np.arange(12,24).reshape(3,4)

In [83]:
# horizontal stacking
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [84]:
# vertical staacting
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])