**Note: In Data Science googling is a very important skill. If you find some difficulties to solve the problem, google it and try to find some clues to solve.**

In [1]:
import numpy as np

###`Q-1` Create a null vector of size 10 but the fifth value which is 1.



In [7]:
#Code here
(np.arange(10) == 4).astype(int)

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

###`Q-2` Ask user to input two numbers a, b. Write a program to generate a random array of shape (a, b) and print the array and avg of the array.

In [19]:
#Code here

a,b = map(int,input().split())
randow_array=np.random.random((a,b))
print(randow_array)
print("___")
np.average(randow_array)


3 4
[[0.3312791  0.42151161 0.53860523 0.8700884 ]
 [0.37312092 0.06739031 0.8547866  0.49445352]
 [0.52405012 0.13352751 0.80873264 0.8206979 ]]
___


0.5198536561826103

###`Q-3`Write a function to create a 2d array with 1 on the border and 0 inside. Take 2-D array shape as (a,b) as parameter to function.

Eg.-
```
[[1,1,1,1],
[1,0,0,1],
[1,0,0,1],
[1,1,1,1]]
```

In [21]:
#Code here
def border(a,b):
    x=np.ones((a,b),dtype=int)
    x[1:-1,1:-1]=0
    return x
border(4,5)

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

###`Q-4` Create a vector of size 10 with values ranging from 0 to 1, both excluded.


In [25]:
#Code here
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

###`Q-5` Can you create a identity mattrix of shape (3,4). If yes write code for it.

In [ ]:
#Code here
# no we can not cretw the 3 X 4 identify matrix

###`Q-6:` Create a 5x5 matrix with row values ranging from 0 to 4.

In [30]:
#Code here
z=np.zeros((5,5),dtype=int)
z+=np.arange(5,dtype=int)
z

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

###`Q-7:`  Consider a random integer (in range 1 to 100) vector with shape `(10,2)` representing coordinates, and coordinates of a point as array is given. Create an array of distance of each point in the random vectros from the given point. Distance array should be interger type.

```
point = np.array([2,3])
```


In [39]:
#code here
random_integer = np.random.randint(1,100,(10,2))
point=np.array([2,3])

np.sqrt(np.sum((random_integer - point)**2 ,axis=1)).astype(int)

array([105,  57,  66, 105, 122,  53,  79,  84, 103,  68])

###`Q-8:` Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [40]:
#Code here
np.unravel_index(100,(6,7,8))


(1, 5, 4)

### `Q-9:` Arrays

You are given a space separated list of numbers. Your task is to print a reversed NumPy array with the element type float.



**Input Format:**

A single line of input containing space separated numbers.

**Output Format:**

Print the reverse NumPy array with type float.

**Example 1:**

Input:

```bash
1 2 3 4 -8 -10
```

Output:

```bash
[-10.  -8.   4.   3.   2.   1.]
```

In [48]:
#Code here
arrray_list = input().strip().split()
np.array(arrray_list[::-1],dtype=np.float32)

1 2 3 4


array([4., 3., 2., 1.], dtype=float32)

### `Q-10:` Elements count

Count the number of elements of a numpy array.



**Example 1:**

Input:
```bash
np.array([])
```

Output:
```bash
elements_count :  0
```

**Example 2:**

Input:
```bash
np.array([1, 2])
```

Output:
```bash
elements_count :  2
```

In [52]:
#Code here
len(input().strip().split())

1 2 3 4 56 


5

### `Q-11:` Softmax function

Create a Python function to calculate the Softmax of the given numpy 1D array. The function only accepts the numpy 1D array, otherwise raise error.

$$\Large \sigma(\vec z)_i = \frac{e^{z_i}}{\sum_{j=i}^{K}{e^{z_j}}}$$

https://en.wikipedia.org/wiki/Softmax_function



**Example 1:**

Input:
```bash
[86.03331084 37.7285648  48.64908087 87.16563062 38.40852563 37.20006318]
```

Output:
```bash
[2.43733249e-01, 2.56112115e-22, 1.41628284e-17, 7.56266751e-01,
       5.05514197e-22, 1.50974911e-22]
```

**Example 2:**

Input:
```bash
[33.17344305 45.61961654 82.05405781 80.9647098  68.82830233 91.52064278]
```

Output:
```bash
[4.57181035e-26, 1.16249923e-20, 7.73872596e-05, 2.60358426e-05,
       1.39571531e-10, 9.99896577e-01]
```

In [55]:
#Code here
l=[33.17344305 ,45.61961654, 82.05405781, 80.9647098,  68.82830233 ,91.52064278]
def sofmax(arr):
    s=sum(np.exp(arr))
    return np.exp(arr)/s
sofmax(l)


array([4.57181033e-26, 1.16249922e-20, 7.73872594e-05, 2.60358426e-05,
       1.39571531e-10, 9.99896577e-01])

### `Q-12:` Vertical stack

Write a python function that accepts infinite number of numpy arrays and do the vertical stack to them. Then return that new array as result. The function only accepts the numpy array, otherwise raise error.



**Example 1:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]
```

Output:

```bash
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
```

**Example 2:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]

c= [[0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

Output:
```bash
[[0.         1.         2.         3.         4.        ]
 [5.         6.         7.         8.         9.        ]
 [1.         1.         1.         1.         1.        ]
 [1.         1.         1.         1.         1.        ]
 [0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

In [61]:
#Coder here
a= np.array([[0, 1, 2, 3, 4],[5, 6, 7, 8, 9]])

b= np.array([[1, 1, 1, 1, 1],[1, 1, 1, 1, 1]])

np.vstack((a,b))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

### `Q-13:` Dates

Create a python function named **date_array** that accepts two dates as string format and returns a numpy array of dates between those 2 dates. The function only accept 2 strings, otherwise raise error. The date format should be like this only: `2022-12-6`. The end date should be included and for simplicity, choose dates from a same year.



**Example 1:**

Input:
```bash
date_array(start = '2020-09-15', end = '2020-09-25')
```

Output:
```bash
['2020-09-15', '2020-09-16', '2020-09-17', '2020-09-18',
 '2020-09-19', '2020-09-20', '2020-09-21', '2020-09-22',
 '2020-09-23', '2020-09-24', '2020-09-25']
```

**Example 2:**

Input:
```bash
date_array(start = '2022-12-01', end = '2022-12-06')
```

Output:
```bash
['2022-12-01', '2022-12-02', '2022-12-03', '2022-12-04', '2022-12-05', '2022-12-06']
```

**Example 3:**

Input:
```bash
date_array(start = '2020-11-25', end = '2020-11-30')
```

Output:
```bash
['2020-11-25', '2020-11-26', '2020-11-27', '2020-11-28',
 '2020-11-29', '2020-11-30']
```

In [65]:
#Code here
import numpy as np
from datetime import datetime

def date_array(start_date, end_date):
    # Check if both inputs are strings
    if not isinstance(start_date, str) or not isinstance(end_date, str):
        raise ValueError("Both inputs must be strings.")
    
    # Convert strings to datetime objects
    start_date = datetime.strptime(start_date, '%Y-%m-%d')
    end_date = datetime.strptime(end_date, '%Y-%m-%d')

    # Check if both dates are in the same year
    if start_date.year != end_date.year:
        raise ValueError("Both dates must be in the same year.")
    
    # Convert datetime objects to numpy date objects
    start_date = np.datetime64(start_date)
    end_date = np.datetime64(end_date)
    
    # Generate array of dates
    dates = np.arange(start_date, end_date + np.timedelta64(1, 'D'), dtype='datetime64[D]')
    
    return dates

date_array(start_date = '2020-11-25', end_date = '2020-11-30')

array(['2020-11-25', '2020-11-26', '2020-11-27', '2020-11-28',
       '2020-11-29', '2020-11-30'], dtype='datetime64[D]')

###`Q-14:` Subtract the mean of each row from a matrix.

In [73]:
#code here

a= np.random.random((5,4))
a- a.mean(axis=0)

array([[-0.43321027,  0.22862712,  0.01189364, -0.42636973],
       [ 0.31651063,  0.27219627, -0.08745735, -0.3414911 ],
       [-0.2187029 ,  0.21597663,  0.27919318,  0.22791105],
       [ 0.33417945, -0.4727011 ,  0.13663675,  0.14991172],
       [ 0.00122309, -0.24409893, -0.34026622,  0.39003807]])

###`Q-15:` Swap column-1 of array with column-2 in the array.

In [ ]:
#Code here


###`Q-16:` Replace odd elements in arrays with -1.

In [80]:
#Code here
a=np.arange(12).reshape(3,4)
a[a%2 ==1 ]= -1
a
        

array([[ 0, -1,  2, -1],
       [ 4, -1,  6, -1],
       [ 8, -1, 10, -1]])

###`Q-17:` Given two arrays of same shape make an array of max out of two arrays. (Numpy way)
```
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])

Result-> [6 3 1 7 8]
```

In [ ]:
#Code here

In [83]:
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])

a[b>a] = b[a<b]
a

array([6, 3, 1, 7, 8])

###`Q-18` Answer below asked questions on given array:
1. Fetch Every alternate column of the array
2. Normalise the given array

https://en.wikipedia.org/wiki/Normalization_(statistics)

There are different form of normalisation for this question use below formula.

$$\large X_{normalized} = \frac{X - X_{min}}{X_{max} - X_{min}}$$

```python
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
```


In [84]:
# Given
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
arr1

array([[1716, 1753, 3666, 1193, 8068],
       [2997, 6974, 8891, 2119, 9175],
       [4233, 6275,  789, 4033, 3110],
       [9654, 2906, 3376,  193, 3664],
       [7076, 5317, 7706, 3211, 6679],
       [3828, 8864, 5412, 8898, 4940],
       [ 466, 6058, 3183,  211, 8400],
       [9503, 5539, 9776, 7847, 9386]])

In [85]:
#Code here
arr1[:,::2]

array([[1716, 3666, 8068],
       [2997, 8891, 9175],
       [4233,  789, 3110],
       [9654, 3376, 3664],
       [7076, 7706, 6679],
       [3828, 5412, 4940],
       [ 466, 3183, 8400],
       [9503, 9776, 9386]])

In [86]:
(arr1 -arr1.min()) / (arr1.max() - arr1.min())

array([[0.15892727, 0.16278827, 0.36241261, 0.10435146, 0.82176771],
       [0.29260148, 0.70760722, 0.90764896, 0.2009809 , 0.93728478],
       [0.42157988, 0.63466555, 0.06219347, 0.40070959, 0.3043932 ],
       [0.98726912, 0.2831055 , 0.33215068, 0.        , 0.3622039 ],
       [0.71825107, 0.53469686, 0.78399249, 0.31493269, 0.67682354],
       [0.37931754, 0.90483147, 0.54461025, 0.90837942, 0.49535636],
       [0.02848795, 0.61202129, 0.31201085, 0.00187833, 0.8564124 ],
       [0.97151205, 0.55786288, 1.        , 0.79870604, 0.95930293]])

###`Q-19:` Write a function which will accept 2 arguments.
First: A 1D numpy array arr

Second: An integer n {Please make sure n<=len(arr)}

Output: The output should be the nth largest item out of the array
```
# Example1 : arr=(12,34,40,7,1,0) and n=3, the output should be 12
# Example2 : arr=(12,34,40,7,1,0) and n=1, the output should be 34
```

In [93]:
#Code here

def nth_largest(arr,n):
    a=np.array(arr)
    a=sorted(a,reverse=1)
    return a[n]
nth_largest(arr=[12,34,40,7,1,0],n=1)


34

###`Q-20:` Create the following pattern without hardcoding. Use only numpy functions and the below input array a.
```
# Input: a = np.array([1,2,3])
# Output: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
```

In [94]:
#code here
a = np.array([1,2,3])
np.r_[np.repeat(a, 3), np.tile(a, 3)]

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])